### ISSUE TITLE
Command line compatibility with dig

### ISSUE THREAD

**Issue by ljliman** [NLnetLabs/dnsi#17]
You seem to be writing a tool to query the DNS with output that is compatiple with that from dig. Would you _PLEASE_ also make the command line flags cut-and-paste compatible with dig?! Dig is industry standard for querying the DNS, and if you want old dogs to use your software, then don't force them to learn a new query language.

There may, of course, be reason to not do that that I'm unaware of, such as intellectual property rights or an urge to change something that you consider bad (if so, why is it bad?) to be better, but unless you have such reasons, I see no reason to create a new user inteface just for the sake of it, or "NIH" (Not Invented Here). Standards are good. Do give us too many to choose from ...

Cheers,
  /Liman

**Comment by Jakker** [comment]
I too argued for a dig-compatible interface. People have complained that for similar reasons, drill was useless as well.

**Comment by partim** [comment]
Our intention is not to create a dig replacement but rather to rethink tooling for inspecting the DNS and investigating possible issues. We felt that dig exists and is perfectly fine for what it does. Our plan is to provide tools that go beyond simple querying – `dnsi lookup` is an, albeit very simple, example of that.

That the output of `dnsi query` is currently very dig-like was mostly due to having to start somewhere. We will probably retain it but are considering changing the default output to something that is more explanatory to non-DNS experts.

In that sense, we don’t aim for everyone currently using dig to switch to dnsi, but rather to create something new that is more friendly to new users. Having command line options more consistent with what people now expect is part of that.

**Comment by ljliman** [comment]
Well, if beginner-friendly and "non-DNS-experts" is what you're after, then I won't be the man saying "it cannot be done" standing in the way of those doing it. Please go ahead! I wish you the best of luck!
